"""
Metric functions for the computer-vision flow-analysis pipeline.

These functions convert tracking outputs into physical and statistical indicators.
"""

from typing import Optional

import numpy as np
import pandas as pd


def pixels_to_physical(
    values_px: pd.Series | np.ndarray | float,
    pixel_to_mm: float = 1.0
):
    """
    Convert pixel measurements to millimeters.

    Parameters
    ----------
    values_px : Series, ndarray, or float
        Measurement in pixels.
    pixel_to_mm : float
        Physical scale conversion factor.

    Returns
    -------
    Series, ndarray, or float
        Measurement in millimeters.
    """
    return values_px * pixel_to_mm


def frames_to_seconds(
    frames: pd.Series | np.ndarray | float,
    frame_rate_fps: float
):
    """
    Convert frame counts to seconds.

    Parameters
    ----------
    frames : Series, ndarray, or float
        Number of frames.
    frame_rate_fps : float
        Frame rate in frames per second.

    Returns
    -------
    Series, ndarray, or float
        Time in seconds.
    """
    if frame_rate_fps <= 0:
        raise ValueError("frame_rate_fps must be positive.")

    return frames / frame_rate_fps


def add_physical_tracking_metrics(
    tracks: pd.DataFrame,
    pixel_to_mm: float,
    frame_rate_fps: float,
    displacement_col: str = "step_displacement_px",
    frame_gap_col: str = "frame_gap"
) -> pd.DataFrame:
    """
    Add physical displacement and velocity columns to a tracking table.

    Parameters
    ----------
    tracks : pd.DataFrame
        Tracking table generated by the tracking module.
    pixel_to_mm : float
        Pixel-to-millimeter conversion factor.
    frame_rate_fps : float
        Frame rate in frames per second.
    displacement_col : str
        Column with frame-to-frame displacement in pixels.
    frame_gap_col : str
        Column with frame gap between detections.

    Returns
    -------
    pd.DataFrame
        Tracking table with physical metrics.
    """
    required_cols = [displacement_col, frame_gap_col]

    missing_cols = [col for col in required_cols if col not in tracks.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns: {missing_cols}")

    output = tracks.copy()

    output["step_displacement_mm"] = pixels_to_physical(
        output[displacement_col],
        pixel_to_mm=pixel_to_mm
    )

    output["time_gap_s"] = frames_to_seconds(
        output[frame_gap_col],
        frame_rate_fps=frame_rate_fps
    )

    output["velocity_mm_s"] = (
        output["step_displacement_mm"] / output["time_gap_s"]
    )

    output.loc[output["time_gap_s"] <= 0, "velocity_mm_s"] = np.nan

    return output


def add_size_metrics(
    detections: pd.DataFrame,
    pixel_to_mm: float,
    area_col: str = "area_px",
    diameter_col: str = "equivalent_diameter_px"
) -> pd.DataFrame:
    """
    Add physical size metrics to a detection table.

    Parameters
    ----------
    detections : pd.DataFrame
        Detection table generated by the segmentation module.
    pixel_to_mm : float
        Pixel-to-millimeter conversion factor.
    area_col : str
        Column with object area in pixels.
    diameter_col : str
        Column with equivalent diameter in pixels.

    Returns
    -------
    pd.DataFrame
        Detection table with physical size metrics.
    """
    output = detections.copy()

    if area_col in output.columns:
        output["area_mm2"] = output[area_col] * (pixel_to_mm ** 2)

    if diameter_col in output.columns:
        output["equivalent_diameter_mm"] = output[diameter_col] * pixel_to_mm

    return output


def summarize_detections(
    detections: pd.DataFrame,
    frame_col: str = "frame_id",
    area_col: str = "area_px",
    diameter_col: str = "equivalent_diameter_px"
) -> pd.DataFrame:
    """
    Summarize object detections by frame.

    Parameters
    ----------
    detections : pd.DataFrame
        Detection table.
    frame_col : str
        Name of the frame column.
    area_col : str
        Name of the area column.
    diameter_col : str
        Name of the equivalent diameter column.

    Returns
    -------
    pd.DataFrame
        Frame-level detection summary.
    """
    if frame_col not in detections.columns:
        raise ValueError(f"Missing required column: {frame_col}")

    agg_dict = {
        "n_objects": (frame_col, "size")
    }

    if area_col in detections.columns:
        agg_dict.update(
            {
                "mean_area_px": (area_col, "mean"),
                "median_area_px": (area_col, "median"),
                "std_area_px": (area_col, "std"),
            }
        )

    if diameter_col in detections.columns:
        agg_dict.update(
            {
                "mean_equivalent_diameter_px": (diameter_col, "mean"),
                "median_equivalent_diameter_px": (diameter_col, "median"),
                "std_equivalent_diameter_px": (diameter_col, "std"),
            }
        )

    return (
        detections
        .groupby(frame_col)
        .agg(**agg_dict)
        .reset_index()
    )


def summarize_tracking(
    tracks: pd.DataFrame,
    track_col: str = "track_id",
    velocity_col: str = "velocity_mm_s",
    displacement_col: str = "step_displacement_mm",
    duration_col: Optional[str] = None
) -> pd.DataFrame:
    """
    Summarize tracking metrics by track.

    Parameters
    ----------
    tracks : pd.DataFrame
        Tracking table.
    track_col : str
        Name of the track ID column.
    velocity_col : str
        Name of the physical velocity column.
    displacement_col : str
        Name of the physical displacement column.
    duration_col : str or None
        Optional duration column.

    Returns
    -------
    pd.DataFrame
        Track-level summary.
    """
    if track_col not in tracks.columns:
        raise ValueError(f"Missing required column: {track_col}")

    agg_dict = {
        "n_detections": (track_col, "size")
    }

    if velocity_col in tracks.columns:
        agg_dict.update(
            {
                "mean_velocity_mm_s": (velocity_col, "mean"),
                "median_velocity_mm_s": (velocity_col, "median"),
                "max_velocity_mm_s": (velocity_col, "max"),
                "std_velocity_mm_s": (velocity_col, "std"),
            }
        )

    if displacement_col in tracks.columns:
        agg_dict.update(
            {
                "total_step_displacement_mm": (displacement_col, "sum"),
                "mean_step_displacement_mm": (displacement_col, "mean"),
            }
        )

    if duration_col is not None and duration_col in tracks.columns:
        agg_dict.update(
            {
                "duration": (duration_col, "max")
            }
        )

    return (
        tracks
        .groupby(track_col)
        .agg(**agg_dict)
        .reset_index()
    )


def campaign_summary(
    detections: Optional[pd.DataFrame] = None,
    tracks: Optional[pd.DataFrame] = None,
    velocity_col: str = "velocity_mm_s",
    diameter_col: str = "equivalent_diameter_mm",
    track_col: str = "track_id",
    frame_col: str = "frame_id"
) -> dict:
    """
    Create a compact campaign-level summary.

    Parameters
    ----------
    detections : DataFrame or None
        Detection table.
    tracks : DataFrame or None
        Tracking table.
    velocity_col : str
        Velocity column name.
    diameter_col : str
        Diameter column name.
    track_col : str
        Track ID column name.
    frame_col : str
        Frame ID column name.

    Returns
    -------
    dict
        Campaign-level metrics.
    """
    summary = {}

    if detections is not None and not detections.empty:
        summary["n_detections"] = int(len(detections))

        if frame_col in detections.columns:
            summary["n_frames_with_detections"] = int(detections[frame_col].nunique())

        if diameter_col in detections.columns:
            summary["mean_diameter_mm"] = float(detections[diameter_col].mean())
            summary["median_diameter_mm"] = float(detections[diameter_col].median())
            summary["std_diameter_mm"] = float(detections[diameter_col].std())

    if tracks is not None and not tracks.empty:
        if track_col in tracks.columns:
            summary["n_tracks"] = int(tracks[track_col].nunique())

        if velocity_col in tracks.columns:
            summary["mean_velocity_mm_s"] = float(tracks[velocity_col].mean())
            summary["median_velocity_mm_s"] = float(tracks[velocity_col].median())
            summary["std_velocity_mm_s"] = float(tracks[velocity_col].std())
            summary["max_velocity_mm_s"] = float(tracks[velocity_col].max())

    return summary


def dataframe_quality_report(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate a simple quality report for a DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame.

    Returns
    -------
    pd.DataFrame
        Quality report with missing values and data types.
    """
    report = pd.DataFrame(
        {
            "column": df.columns,
            "dtype": [str(dtype) for dtype in df.dtypes],
            "n_missing": df.isna().sum().values,
            "pct_missing": (df.isna().mean().values * 100),
            "n_unique": df.nunique(dropna=True).values,
        }
    )

    return report


def remove_unrealistic_values(
    df: pd.DataFrame,
    column: str,
    min_value: Optional[float] = None,
    max_value: Optional[float] = None
) -> pd.DataFrame:
    """
    Remove rows with unrealistic values in a selected numeric column.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame.
    column : str
        Column to check.
    min_value : float or None
        Minimum accepted value.
    max_value : float or None
        Maximum accepted value.

    Returns
    -------
    pd.DataFrame
        Filtered DataFrame.
    """
    if column not in df.columns:
        raise ValueError(f"Missing required column: {column}")

    output = df.copy()

    if min_value is not None:
        output = output[output[column] >= min_value]

    if max_value is not None:
        output = output[output[column] <= max_value]

    return output.reset_index(drop=True)


def compute_flow_metrics(
    tracks: pd.DataFrame,
    pixel_to_mm: float,
    frame_rate_fps: float
) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """
    High-level function to compute flow-related metrics from tracks.

    Parameters
    ----------
    tracks : pd.DataFrame
        Tracking table generated by `src.tracking`.
    pixel_to_mm : float
        Pixel-to-millimeter conversion factor.
    frame_rate_fps : float
        Frame rate in frames per second.

    Returns
    -------
    tuple
        tracks_with_metrics, track_summary, campaign_metrics
    """
    tracks_with_metrics = add_physical_tracking_metrics(
        tracks=tracks,
        pixel_to_mm=pixel_to_mm,
        frame_rate_fps=frame_rate_fps
    )

    track_summary = summarize_tracking(tracks_with_metrics)

    campaign_metrics = campaign_summary(
        detections=None,
        tracks=tracks_with_metrics
    )

    return tracks_with_metrics, track_summary, campaign_metrics
